#!/bin/sh
# Refuses a populated destination; never drops or truncates an existing dataset.
set -eu
[ "${ELEVATEU_REHEARSAL:-}" = 1 ] && [ "${MYSQL_DATABASE:-}" = elevateu_audit ] || {
    echo 'This helper only restores into the explicitly enabled synthetic audit database.' >&2
    exit 1
}
export MYSQL_PWD="${MYSQL_ROOT_PASSWORD:?Test database password required}"
tables=$(mysql -uroot -Nse "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='elevateu_audit'")
[ "$tables" = 0 ] || { echo 'Destination contains tables; restore refused.' >&2; exit 1; }
[ -s /tmp/elevateu-audit.sql ] || { echo 'Missing or empty backup.' >&2; exit 1; }
# Only restore the trusted synthetic dump generated by backup-audit-db.sh.
# SQL dumps are executable code; this is not a sandbox for arbitrary dumps.
mysql -uroot --default-character-set=utf8mb4 elevateu_audit < /tmp/elevateu-audit.sql
echo 'Logical restore completed; preflight, hashes and application tests are still required.'
